spring:
  application:
    name: clima
  redis:
    host: localhost
    port: 6379
    password: admin123
    timeout: 2000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASS}

cache:
  weather:
    ttl-minutes: 15

server:
  port: 0

weatherstack:
  api-key: ${WEATHER_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false

mq:
  queue:
    clima-request: clima-request
    clima-response: clima-response