spring:
  application:
    name: discovery
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASS}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false